apiVersion: apps/v1
kind: Deployment
metadata:
  name: clarus-site
  labels:
    app: clarus-site
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clarus-site
      tier: frontend
  template:
    metadata:
      labels:
        app: clarus-site
        tier: frontend
    spec:
      containers:
      - name: clarus
        image: localhost:5000/clarus-site:v1
        ports:
        - containerPort: 80
